### ISSUE TITLE
NuGet references Windsor 3.2.1, but actually has a dependency on 3.3

### ISSUE THREAD

**Issue by agross** [NancyFx/Nancy.Bootstrappers.Windsor#22]
I hope the title says it all.

I suggest also not to define an open version constraint in the nuspec as it's currently the case (`>= 3.2.1`). What if Windsor 4.0 comes out with breaking changes? If you use a package manager like [Paket](https://fsprojects.github.io/Paket) you'll find issues with version constraints very often.

**Comment by khellang** [comment]
The title is stating a fact. Yes, it looks like the nuspec wasn't updated when the last version was bumped. But what this issue fails to mention is what the problem is. Are you getting errors? Is it just a matter of updating the Windsor package? What's the issue here?

**Comment by khellang** [comment]
> What if Windsor 4.0 comes out with breaking changes?

What if Windsor 4.0 comes out *without* breaking changes, at least not the for APIs that we're depending on. Then we'd have to release a new package just to update the metadata. Thanks, but no thanks :smile:

**Comment by agross** [comment]
When your dependency manager follows a "min" strategy to resolve packages, you'll get 3.2.1. Without further work (binding redirects), your program will fail to run because N.B.Windsor wants Castle.Windsor 3.3, but sees 3.2.1.

**Comment by agross** [comment]
> What if Windsor 4.0 comes out without breaking changes

I guess you could argue both ways. OK, I'll accept that for now and have Paket follow a min version strategy (and always take the oldest dependencies).

> Yes, it looks like the nuspec wasn't updated when the last version was bumped. 

If you want to remove that error for future releases, Paket has a nice feature to [construct the nuspec dependencies](https://fsprojects.github.io/Paket/template-files.html) from your actual `paket.dependencies` file.

**Comment by khellang** [comment]
This was updated a while ago; https://github.com/NancyFx/Nancy.Bootstrappers.Windsor/issues
